version: '3.1' # version of the file
services:
  my-app: #deployment
    image: 587424096316.dkr.ecr.us-east-1.amazonaws.com/my-node-app:1.0 #aws ecr
    ports: 
     - 3000:3000
  mongodb: #name of the container
    image: mongo # image of the container
    ports:
     - 27017:27017 # port that will locally and in the container respectively
    environment: # the environment attributes
     -  MONGO_INITDB_ROOT_USERNAME=admin
     -  MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db  # database entry
  mongo-express: #name of the container
    image: mongo-express #image of the container
    ports:
     - 8081:8081 # port that will locally and in the container respectively
    environment: # the environment attributes
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo-data:
    driver: local # storing it